posts/urls.py
from django.conf.urls import url
from .import views

# urlpatterns = [
#     url(r'^$', views.posts_list, name='home'),
#     url(r'^create/$', views.posts_create, name='create'),
#     url(r'^(?P<id>\d+)/$', views.posts_detail, name='detail'),
#     url(r'^(?P<id>\d+)/edit/$', views.posts_update, name='update'),
#     url(r'^(?P<id>\d+)/delete/$', views.posts_delete, name='delete'),
#     ]

resume/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


from posts import views
from resume import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^$', views.posts_list, name='home'),
    url(r'^top/$', views.posts_list,{'sort':'top'}, name='home_top'),
    url(r'^old/$', views.posts_list,{'sort':'old'}, name='home_old'),
    url(r'^create/$', views.posts_create, name='create'),
    url(r'^(?P<id>\d+)/$', views.posts_detail, name='detail'),
    url(r'^(?P<id>\d+)/edit/$', views.posts_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', views.posts_delete, name='delete'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^(?P<user_id>\d+)/profile/$', views.view_profile, name='view_profile'),
    url(r'^my_mails/$', views.my_mails, name='my_mails'),
    url(r'^(?P<user_id>\d+)/mail_to/$', views.mail_to, name='mail_to'),
    ]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models


# Create your models here.
class MailModel(models.Model):
    sender = models.ForeignKey(User, related_name='sender1')
    recipient = models.ForeignKey(User, related_name='recipient2')
    content = models.TextField(max_length=600)
    timestamp = models.DateTimeField(auto_now_add=True)


class PlusModel(models.Model):
    on_rating = models.ForeignKey('Post')
    user_plus = models.PositiveIntegerField()

    def __str__(self):
        return str(self.user_plus)


class MinusModel(models.Model):
    on_rating = models.ForeignKey('Post')
    user_minus = models.PositiveIntegerField()

    def __str__(self):
        return str(self.user_minus)


class CommentModel(models.Model):
    user = models.ForeignKey(User)
    in_post = models.ForeignKey('Post')
    content = models.TextField('Your comment', max_length=600)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'id': self.in_post_id})


class Post(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=120)
    image = models.FileField(null=True, blank=True)
    content = models.TextField()
    updated = models.DateTimeField('Was updated', auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField('Was created', auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'id': self.id})

    def get_rating(self):
        plus = PlusModel.objects.filter(on_rating=self.id).count()
        minus = MinusModel.objects.filter(on_rating=self.id).count()
        return plus - minus

    class Meta:
        ordering = ["-updated", "-timestamp"]


class ContactModel(models.Model):
    name = models.CharField('Name/Organization', max_length=120)
    email = models.EmailField(blank=True, null=True)
    subject = models.CharField(max_length=120, blank=True)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)


class ProfileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(blank=True, null=True, max_length=50)
    last_name = models.CharField(blank=True, null=True, max_length=50)
    avatar = models.ImageField(blank=True, null=True)
    # gender
    Male = 'ml'
    Female = 'fm'
    Male_to_Female = 'mlf'
    Female_to_Male = 'ftm'
    Two_spirit = '2sp'
    Other = 'oth'
    gender_choices = (
        (Male, 'Male'),
        (Female, 'Female'),
        (Male_to_Female, 'Male to Female'),
        (Female_to_Male, 'Female to Male'),
        (Two_spirit, 'Two spirit'),
        (Other, 'Other'),
    )
    gender = models.CharField(max_length=3, choices=gender_choices, default=Other)

    def get_user_score(self):
        posts = Post.objects.filter(user=self.user)
        plus = 0
        minus = 0
        for post in posts:
            plus += PlusModel.objects.filter(on_rating=post).count()
            minus += MinusModel.objects.filter(on_rating=post).count()
        return plus - minus

    def get_comment_count(self):
        return CommentModel.objects.filter(user=self.user).count()

    def get_posts_count(self):
        return Post.objects.filter(user=self.user).count()

    def get_mail_count(self):
        return MailModel.objects.filter(recipient=self.user).count()

    def __str__(self):
        return self.user.get_username()

posts/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect, Http404, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.datastructures import MultiValueDictKeyError
from django.db.models import Q

from .form import PostModel, ContactForm, ProfileForm, CommentModelForm
from posts.models import Post, ProfileModel, CommentModel, PlusModel, MinusModel, ContactModel, MailModel


def my_mails(request):
    mails = MailModel.objects.all().filter(recipient=request.user).order_by('-timestamp')
    messageid = request.POST.get('delete','')
    if request.method == 'POST' and request.POST.get('delete',''):
        message = get_object_or_404(MailModel, id=messageid)
        message.delete()
    context = {
        'mails': mails,
    }
    return render(request, 'posts/my_mails.html', context)


def mail_to(request, user_id):
    send = False
    to_user = get_object_or_404(User, id=user_id)
    if request.method == 'POST' and request.user.is_authenticated() and request.POST.get('content', ''):
        form = MailModel(
            recipient=to_user,
            sender=request.user,
            content=request.POST.get('content')
        )
        form.save()
        messages.success(request, 'You message was successfully sended')
        send = True
    context = {
        'send':send,
        'to_user':to_user
    }
    return render(request, 'posts/mail_to.html', context)


def view_profile(request, user_id):
    user_name = get_object_or_404(User, id=user_id)
    user_profile = get_object_or_404(ProfileModel, user=user_name)
    user_post = Post.objects.all().filter(user=user_id)
    context = {
        'user_profile': user_profile,
        'user_post': user_post,
    }
    return render(request, 'posts/view_profile.html', context)


def profile(request):
    if not request.user.is_authenticated():
        return redirect('registration_register')
    try:
        profile = request.user.profilemodel
    except ProfileModel.DoesNotExist:
        profile = ProfileModel(user=request.user)

    if request.method == 'POST':
        form_profile = ProfileForm(request.POST, request.FILES, instance=profile)
        if form_profile.is_valid():
            form_profile.save()
            messages.success(request, 'Your profile was successfully edited')
            # return redirect('home')
    else:
        form_profile = ProfileForm(instance=profile)

    user_post = Post.objects.all().filter(user=request.user)
    context = {
        'user_post': user_post,
        'form_profile': form_profile,
    }
    return render(request, 'posts/profile.html', context)


def about(request):
    return render(request, 'posts/about.html')


def contact(request):
    form = ContactForm(request.POST or None)
    form_title = 'Contact form:'
    if request.method == 'POST' and form.is_valid():
        form_title = 'Your message was sent successfully!'
        form.save()
        form = ''
    if request.user.is_superuser and request.method == 'POST' and request.POST['contact_id']:
        contact_id = request.POST['contact_id']
        ContactModel.objects.filter(id=contact_id).delete()
    contacts = ContactModel.objects.all()
    context = {
        'contacts': contacts,
        'form_title': form_title,
        'form': form,
    }
    return render(request, 'posts/contact.html', context)


def posts_list(request, sort=''):
    print('POST_LIST', request.POST)
    # if user dont have profile
    if request.user.is_authenticated():
        try:
            profile = request.user.profilemodel
        except ProfileModel.DoesNotExist:
            profile = ProfileModel(user=request.user)
            profile.save()
    # sort
    if not sort:
        model_title = Post.objects.all()
    elif sort == 'top':
        unsorted_results = Post.objects.all()
        model_title = sorted(unsorted_results, key=lambda t: t.get_rating(), reverse=True)
    elif sort == 'old':
        model_title = Post.objects.all().reverse()
    # paginator
    query = request.GET.get('q')
    if query:
        model_title = Post.objects.all().filter(Q(title__icontains=query) | Q(content__icontains=query))
    paginator = Paginator(model_title, 5)
    page = request.GET.get('page')
    try:
        model_title_p = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        model_title_p = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        model_title_p = paginator.page(paginator.num_pages)

    # rating in post, user can vote by adding 1 to plus OR 1 minus
    vote_up = request.POST.get('vote_up', '')
    vote_down = request.POST.get('vote_down', '')
    vote_valid = False
    if vote_up or vote_down:
        vote_valid = True

    if not request.user.is_authenticated() and vote_valid:
        # messages.error(request, 'Please register or login to vote')
        message = {}
        message['rating'] = 'Register or login to vote'
        message['post_id'] = vote_down or vote_up
        return JsonResponse(message)

    if vote_valid and request.user.is_authenticated():
        # just normal plus/minus logic
        user_vote = request.user.id
        post = get_object_or_404(Post, id=vote_up or vote_down)
        if vote_up:
            if PlusModel.objects.filter(on_rating=post, user_plus=user_vote):
                pass
            elif MinusModel.objects.filter(on_rating=post, user_minus=user_vote):
                MinusModel.objects.filter(on_rating=post, user_minus=user_vote).delete()
            else:
                PlusModel(on_rating=post, user_plus=user_vote).save()

        if vote_down:
            if MinusModel.objects.filter(on_rating=post, user_minus=user_vote):
                pass
            elif PlusModel.objects.filter(on_rating=post, user_plus=user_vote):
                PlusModel.objects.filter(on_rating=post, user_plus=user_vote).delete()
            else:
                MinusModel(on_rating=post, user_minus=user_vote).save()
        # message to AJAX
        message = {}
        message['rating'] = post.get_rating()
        message['post_id'] = vote_down or vote_up
        return JsonResponse(message)

    context = {
        'model_title': model_title_p,
    }
    return render(request, 'posts/home.html', context)


def posts_create(request):
    if not request.user.is_authenticated() and not request.user.is_superuser:
        return redirect('registration_register')
    form = PostModel(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, 'Post successfully created')
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'form': form
    }
    return render(request, 'posts/create.html', context)


def posts_detail(request, id=None):
    instance = get_object_or_404(Post, id=id)
    comments = CommentModel.objects.filter(in_post=id).order_by('-timestamp')
    send_form = request.POST.get('Send', False)
    form = CommentModelForm(request.POST or None)
    if request.method == 'POST' and form.is_valid() and send_form:
        pre_form = form.save(commit=False)
        pre_form.user = request.user
        pre_form.in_post_id = id
        pre_form.save()
        form = CommentModelForm()
        # return HttpResponseRedirect(instance.get_absolute_url())

    # # redirecting AJAX to home: '/'
    # vote_up = request.POST.get('vote_up', '')
    # vote_down = request.POST.get('vote_down', '')
    # vote_valid = False
    # if vote_up or vote_down:
    #     vote_valid = True
    #
    # if not request.user.is_authenticated() and vote_valid:
    #     messages.error(request, 'Please register or login to vote')
    #
    # if vote_valid and request.user.is_authenticated():
    #     # just normal plus/minus logic
    #     user_vote = request.user.id
    #     if vote_up:
    #         post = get_object_or_404(Post, id=vote_up)
    #         if PlusModel.objects.filter(on_rating=post, user_plus=user_vote):
    #             pass
    #             messages.error(request, 'You already added positive vote to this post')
    #         elif MinusModel.objects.filter(on_rating=post, user_minus=user_vote):
    #             MinusModel.objects.filter(on_rating=post, user_minus=user_vote).delete()
    #             messages.info(request, 'Your negative vote was successfully removed')
    #         else:
    #             PlusModel(on_rating=post, user_plus=user_vote).save()
    #             messages.success(request, 'Your positive vote was successfully added')
    #
    #     if vote_down:
    #         post = get_object_or_404(Post, id=vote_down)
    #         if MinusModel.objects.filter(on_rating=post, user_minus=user_vote):
    #             pass
    #             messages.error(request, 'You already added negative vote to this post')
    #         elif PlusModel.objects.filter(on_rating=post, user_plus=user_vote):
    #             PlusModel.objects.filter(on_rating=post, user_plus=user_vote).delete()
    #             messages.info(request, 'Your positive vote was successfully removed')
    #         else:
    #             MinusModel(on_rating=post, user_minus=user_vote).save()
    #             messages.success(request, 'Your negative vote was successfully added')

    context = {
        'title': instance.title,
        'instance': instance,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/detail.html', context)


def posts_update(request, id=None):
    instance = get_object_or_404(Post, id=id)
    author = request.user == instance.user

    if not author and not request.user.is_superuser:

posts/templates/posts/about.html
{% extends 'posts/base.html' %}
{% load static %}

{% block active_about %}
    class='active'
{% endblock %}


{% block title %}
    About
{% endblock %}


{% block content_title %}
    <div class=" container-fluid" style="margin-top: -20px">
        <div class="jumbotron">
            <h2 class="text-center">About</h2>
        </div>
    </div>
{% endblock %}


{% block content %}
    <div class="col-sm-8 blog-main" style="margin-top: 50px">
        <p>
            I am a junior web developer based in Minsk, Belarus.

            My interest is being a full-stack developer. Being involved in everything from the overall direction of a
            project and the actual implementation. I have some experience with Django
            and have worked with front-end tools such as Bootstrap.</p><br>

        <h3> Tools and technologies: </h3>

        <p><strong>Back-end:</strong>Django Framework, Python <br>
            <strong>Front-end:</strong> HTML + CSS, Bootstrap<br>
            <strong>Tools:</strong> Git, PyCharm </p>
    </div>
    <div class="col-sm-4  blog-main" style="margin-top: 50px">
        <img src="{% static 'posts/img/IMG_7194.jpg' %}" class="img-responsive"/>
    </div>
{% endblock %}

posts/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'posts/img/favicon.ico' %}">

    <title>Blog|{% block title %}{% endblock %}</title>

    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'posts/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'posts/font-awesome/css/font-awesome.min.css' %}">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'posts/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'posts/css/custom_style.css' %}" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        {% block style %}
        {% endblock %}
    </style>
</head>

<body>
<!-- Static navbar -->
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li{% block active_home %}{% endblock %}><a href="{% url 'home' %}">Home</a></li>
                <li{% block active_about %}{% endblock %}><a href="{% url 'about' %}">About</a></li>
                <li{% block active_contact %}{% endblock %}><a href="{% url 'contact' %}">Contact</a></li>

            </ul>


            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated and not '/accounts/login' in request.get_full_path %}
                    <li><h4 style="margin-top: 18px"> Welcome,<span style="color: cyan "> {{ request.user }}!</span>
                    </h4></li>
                    <li><a href="{% url 'profile' %}">Profile</a></li>
                    <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'registration_register' %}">Register</a></li>
                    {#                    <li><button style="margin-top: 6px" class="btn btn-default">Register</button> </li>#}
                    {#                    <li><a href="{% url 'auth_login' %}">Login</a></li>#}
                    </ul>
                {% endif %}

            {% if not request.user.is_authenticated and not '/accounts/login' in request.get_full_path %}
                <form class="navbar-form navbar-right" method="POST" action="{% url 'auth_login' %}"> {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="username" placeholder="Username"/>
                    </div>

                    <div class="form-group">
                        <input type="password" class="form-control" name="password" placeholder="Password"/>
                    </div>

                    <button type="submit" class="btn btn-default">Login</button>
                </form>
            {% endif %}
        </div><!--/.nav-collapse -->
    </div>
</nav>


<div class="container">
    {% include 'posts/messages.html' %}

    {% block content_title %}
    {% endblock %}

    <div style="margin-bottom: 50px" class="row">

        {% block content %}
        {% endblock content %}


    </div><!-- /.row -->

</div><!-- /.container -->

<footer class="blog-footer">
    <p>Blog was created by Artsiom Ivanov</p>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'posts/js/Homejs.js' %}"></script>
<script src="{% static 'posts/js/jquery.min.js' %}"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="{% static 'posts/js/bootstrap.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'posts/js/ie10-viewport-bug-workaround.js' %}"></script>
</body>
</html>

posts/templates/posts/contact.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}

{% block active_contact %}
    class='active'
{% endblock %}


{% block title %}
    Contact
{% endblock %}


{% block content_title %}
    <div class=" container-fluid" style="margin-top: -20px">
        <div class="jumbotron">
            <h2 class="text-center">Contact</h2>
        </div>
    </div>
{% endblock %}


{% block content %}
    {% if not request.user.is_superuser %}
        <div class="col-sm-8 blog-main" style="margin-top: 50px">
            <h2>{{ form_title }}</h2>
            {% if form %}
                <form method="POST">{% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" value="Send" class="btn btn-primary">
                </form>
            {% endif %}
        </div>
        <div class="col-sm-3 col-sm-offset-1 blog-main" style="margin-top: 50px">
            <h2>Contact information:</h2>
            <p>Artsiom Maratovich Ivanou <br>
                +375(29)164-74-83 <br>
                buggy.the.clown.md@gmail.com </p>
        </div>
    {% else %}
        {% if contacts %}
            {% for contact in contacts %}
                <div class="row" style="margin-bottom: 20px">
                    <strong>Name/Organization: </strong>{{ contact.name }}<br>
                    <strong>Email:</strong> {{ contact.email }}<br>
                    <strong>Subject: </strong>{{ contact.subject }}<br>
                    <strong>Content: </strong>{{ contact.content }}<br>
                    <strong>Timestamp: </strong>{{ contact.timestamp }}<br>
                    <form method="POST"> {% csrf_token %}
                        <input hidden name="contact_id" value="{{ contact.id }}">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                </div>
            {% endfor %}
        {% endif %}
    {% endif %}
{% endblock %}

posts/templates/posts/create.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create
{% endblock %}

{% block content %}
    <div class="col-sm-8 col-sm-offset-2">
        <h2>Form:</h2>
        <form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Create Post" class="btn btn-success"/>
        </form>
    </div>
{% endblock %}

posts/templates/posts/mail_to.html
{% extends 'posts/base.html' %}


{% block title %}
    Mail to
{% endblock %}


{% block content %}
    {% if not send %}
        <div class="col-sm-10 col-sm-offset-2">
            <form class="form-horizontal" role="form" method="post"> {% csrf_token %}
                <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">Send to</label>
                    <div class="col-sm-5" style="margin-top: 10px">
                        {#                <input type="text" class="form-control" id="name" name="name"  value="{{ to_user }}">#}
                        {{ to_user }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="message" class="col-sm-2 control-label">Message</label>
                    <div class="col-sm-5">
                        <textarea class="form-control" rows="4" id="message" name="content"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2">
                        <input id="submit" name="submit" type="submit" value="Send" class="btn btn-primary">
                    </div>
                </div>
            </form>
        </div>
    {% endif %}
{% endblock %}

posts/templates/posts/messages.html
{#{% block messages %}#}
{#    {% if messages %}#}
{#        <ul class="messages">#}
{#            {% for message in messages %}#}
{#                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    {% endif %}#}
{#{% endblock %}#}


{% block messages %}
    {% if messages %}
        {% for message in messages %}
            {% ifequal message.tags 'success' %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endifequal %}

            {% ifequal message.tags 'info' %}
                <div class="alert alert-info" role="alert">
                    {{ message }}
                </div>
            {% endifequal %}

            {% ifequal message.tags 'warning' %}
                <div class="alert alert-warning" role="alert">
                    {{ message }}
                </div>
            {% endifequal %}


            {% ifequal message.tags 'error' %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endifequal %}
        {% endfor %}
    {% endif %}
{% endblock %}

posts/templates/posts/view_profile.html
{% extends 'posts/base.html' %}
{% load static %}

{% block title %}
    {{ user_profile }}
{% endblock %}


{% block content_title %}
    <div class=" container-fluid" style="margin-top: -20px">
        <div class="jumbotron">
            <h2 class="text-center">{{ user_profile }} profile</h2>
        </div>
    </div>
{% endblock %}


{% block content %}
    <div class="col-sm-6 blog-main" style="margin-top: 50px">
        <ul class="list-group">
            <li class="list-group-item"> Username - {{ user_profile }} </li>
            <li class="list-group-item"> First name - {{ user_profile.first_name }} </li>
            <li class="list-group-item"> Last name - {{ user_profile.last_name }} </li>
            <li class="list-group-item"> Gender - {{ user_profile.get_gender_display }} </li>
        </ul>
    </div>
    <div class="col-sm-4 col-sm-offset-2  blog-main" style="margin-top: 50px">
        {% if user_profile.avatar %}
            <img src="{{ user_profile.avatar.url }}" class="img-responsive"/>
        {% else %}
            <img src="{% static 'posts/img/unregistered.png' %}" class="img-responsive"/>
        {% endif %}
        <br>
        Date of join Tidjei's blog: <br>
        {{ user_profile.user.date_joined|date }} <br>
        Total user's posts rating: {{ user_profile.get_user_score }}
    </div>
    <br>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
            <h2>Posts:</h2>
        </div>
    </div>

    {% for i in user_post %}
{#        <div class="row" style="margin-top: 50px">#}
{#            <div class="col-sm-10 col-sm-offset-1">#}
{#                <div class="thumbnail">#}
{#                    <h3>{{ i.title }} <br>#}
{#                        <small>{{ i.updated|timesince }} ago</small>#}
{#                    </h3>#}
{#                    <p>Author:<a href="{% url 'view_profile' i.user.id %}"> {{ i.user }} </a></p>#}
{#                    {% if i.image %}#}
{#                        <img src="{{ i.image.url }}" class="img-responsive"/>#}
{#                    {% endif %}#}
{##}
{#                    <div class="caption">#}
{#                        <p>{{ i.content|linebreaks|truncatechars:500 }}</p>#}
{#                        <p><a href="{{ i.get_absolute_url }}" class="btn btn-primary" role="button">View</a>#}
{#                            {% if request.user == i.user or request.user.is_superuser %}#}
{#                                <a href="{% url 'update' i.id %}" class="btn btn-info"#}
{#                                   role="button">Edit</a>#}
{#                                <a href="{% url 'delete' i.id %}" class="btn btn-warning" role="button">Delete</a>#}
{#                                </p>#}
{#                            {% endif %}#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
        {% include 'posts/view_post_list.html' %}
    {% endfor %}
{% endblock %}